version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify Node.js version if using AWS CodeBuild with runtime-versions support.
    commands:
      - echo "Installing Yarn..."
      - npm install -g yarn
      - echo "Yarn version:"
      - yarn -v
  pre_build:
    commands:
      - echo "Installing source dependencies..."
      - yarn install
  build:
    commands:
      - echo "Building the project..."
      - yarn build
  post_build:
    commands:
      - echo "Syncing build folder to S3..."
      - aws s3 sync dist/ s3://$S3_BUCKET_NAME/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - echo "Build completed. Artifacts are located in the dist folder."

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
