version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Node.js and Yarn...
      - curl -o- https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$PATH"
      - echo Installing source dependencies....
      - yarn install
  build:
    commands:
      - echo Building...
      - yarn build
  post_build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /
      - echo Build completed. Artifacts are located in the dist folder.

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
