 version: 0.2

phases:
    pre_build:
        commands:
            - echo Installing source NPM dependencies....
            - npm install
    build:
        commands:
            - echo Building...
            - npm run build
    post_build:
        commands:
            - echo Deploying to S3...
            - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete
            - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /

artifacts:
    files:
        - '**/*'
    base-directory: 'build'