version: 0.2

phases:
  install:
    commands:
      - echo update npm...
      - npm install -g n
      - n latest
      - npm update -g npm
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source dependencies....
      - yarn install
  build:
    commands:
      - echo Building...
      - yarn build
  post_build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /
      - echo Build completed. Artifacts are located in the dist folder.

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
